# Generated by Django 2.2 on 2019-05-13 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registerPlate', models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Wrong Plate number format', regex='^(\\w+\\d+|\\d+\\w+)+$')])),
                ('maxPassengerAllowed', models.PositiveIntegerField()),
                ('productionDate', models.DateField()),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=25)),
                ('carCategory', models.CharField(choices=[('First Class', 'First Class'), ('Bizness Class', 'Bizness Class'), ('Economic Class', 'Economic Class')], default='Economic Class', max_length=17)),
                ('engineType', models.CharField(choices=[('Electric', 'Electric'), ('Normal', 'Normal'), ('Hybrid', 'Hybrid')], default='Normal', max_length=8)),
            ],
        ),
    ]
